import { esc, now } from './clock.mjs';
import { contactsFor, contactLabel } from './model.mjs';
import { OS_TABS, JOB_STATES, PLACE_TYPES, visibleRecord, editableRecord, callsForViewer, cityMap } from './os-model.mjs';
import { actorForDevice, hasLedger, isNPCDevice } from './wealth.mjs';
import { protectedStorage } from './store.mjs';
import { canReadDocument, canEditDocument } from './documents-model.mjs';
export const icon = name => `<i class="fa-solid fa-${name}" aria-hidden="true"></i>`;
export const button = (op,label,attrs='',symbol='') => `<button type="button" data-action="osAction" data-os="${op}" ${attrs}>${symbol?icon(symbol):''}${esc(label)}</button>`;
const direct = (action,label,symbol='') => `<button type="button" data-action="${action}">${symbol?icon(symbol):''}${esc(label)}</button>`;
const badge = s => `<span class="os-tag">${esc(s)}</span>`;
const empty = (title,description) => `<div class="os-empty">${icon('satellite-dish')}<h3>${esc(title)}</h3><p>${esc(description)}</p></div>`;
const section = (title,body,actions='') => `<section class="os-card"><div class="os-card-head"><h3>${esc(title)}</h3>${actions}</div>${body}</section>`;
const img = (src,cls='os-thumb') => src?`<img class="${cls}" src="${esc(src)}" alt="" loading="lazy">`:'';
const date = ms => new Date(ms).toLocaleDateString('ru-RU',{day:'2-digit',month:'short'});
const money = value => Number(value||0).toLocaleString('ru-RU')+' эдди';
const searchable = value => esc(String(value).toLocaleLowerCase('ru-RU'));
export function contactPortrait(state,number,other) { return state.os?.contacts?.[number]?.[other]?.avatar || state.os?.profiles?.[other]?.avatar || ''; }
export function avatar(src) { return src?img(src,'os-avatar'):`<span class="os-avatar os-avatar-empty">${icon('user')}</span>`; }
function search(app,placeholder) { return `<label class="os-search">${icon('magnifying-glass')}<input type="search" class="os-search-input" aria-label="${esc(placeholder)}" placeholder="${esc(placeholder)}" value="${esc(app.osSearch?.[app.osTab]||'')}"></label>`; }
const start = (title,sub,actions='') => `<div class="os-page-heading"><div><span class="os-kicker">${esc(sub)}</span><h2>${esc(title)}</h2></div><div class="os-actions">${actions}</div></div>`;
const meta = (key,value) => `<div class="os-detail"><span>${esc(key)}</span><strong>${esc(value || '—')}</strong></div>`;
export function OSContext(app,state) {
  const number=app.num, device=state.devices[number], os=state.os??{}, user=game.user;
  const page=app.osTab||'home', profile=os.profiles?.[number]??{}, map=cityMap(state);
  const npcPayer=user.isGM&&isNPCDevice(device),monitoring=user.isGM&&app.osCallScope!=='mine';
  const available=key=>Object.values(os[key]??{}).filter(r=>visibleRecord(state,r,user));
  const jobs=available('jobs'),places=available('places'),articles=available('articles').sort((a,b)=>b.createdAt-a.createdAt);
  const contacts=number?contactsFor(state,number):[];
  const devices=Object.values(state.devices).filter(d=>user.isGM||d.owner===user.id);
  const actor=device?actorForDevice(device):null;
  const canWallet=!npcPayer && actor && (user.isGM||actor.isOwner) && hasLedger(actor);
  const reminders=Object.values(os.reminders?.[number]??{}).sort((a,b)=>Number(a.done)-Number(b.done)||a.due-b.due);
  const calls=callsForViewer(state,user,number,monitoring?'all':'mine');
  const activeCallCount=calls.filter(c=>c.status!=='ended').length;
  const unread=contacts.reduce((s,c)=>s+c.unread,0);
  const nav=OS_TABS.map(([key,label,symbol])=>`<button type="button" data-action="osAction" data-os="nav" data-tab="${key}" class="${page===key?'on':''}" aria-label="${label}" aria-current="${page===key?'page':'false'}">${icon(symbol)}<span>${label}</span>${key==='messages'&&unread?`<b>${unread}</b>`:key==='calls'&&activeCallCount?`<b>${activeCallCount}</b>`:''}</button>`).join('');
  if (!device) return {osContent:'',osNav:nav,osMessages:page==='messages'};
  const contactName=n=>contactLabel(state,number,n);
  const contactCard=c=>{
    const info=os.contacts?.[number]?.[c.num]??{},p=os.profiles?.[c.num]??{};
    return `<article class="os-contact-row" data-os-search="${searchable([c.name,c.num,info.category,info.note].join(' '))}">${avatar(contactPortrait(state,number,c.num))}<div class="os-grow"><div class="os-card-head"><h3>${esc(c.name)}</h3>${button('favorite',info.favorite?'Избранный':'В избранное',`data-num="${esc(c.num)}" aria-pressed="${!!info.favorite}"`,'star')}</div><div class="os-muted">${esc(c.num)} ${info.category?badge(info.category):''}</div>${p.role?`<p>${esc(p.role)}</p>`:''}${p.status?badge(({online:'На связи',away:'Занят',offline:'Недоступен'})[p.status]||''):''}${info.note?`<p class="os-line-clamp">${esc(info.note)}</p>`:''}<div class="os-actions">${button('message','Написать',`data-num="${esc(c.num)}"`,'comment')}${button('call','Позвонить',`data-num="${esc(c.num)}"`,'phone')}${button('pay','Перевод',`data-num="${esc(c.num)}"`,'coins')}${button('contact','Карточка',`data-num="${esc(c.num)}"`,'pen')}</div></div></article>`;
  };
  const jobCard=j=>`<article class="os-job" data-os-search="${searchable(j.title+' '+j.body+' '+j.fixer)}">${img(j.image)}<div class="os-grow"><div class="os-card-head"><h3>${esc(j.title)}</h3>${badge(JOB_STATES[j.status])}</div><p>${esc(j.body)}</p><div class="os-actions"><span class="os-gold">${money(j.reward)}</span>${j.fixer?badge(j.fixer):''}${j.due?badge(j.due):''}${!j.published?badge('Черновик мастера'):''}</div><ul class="os-checklist">${(j.steps??[]).map(s=>`<li><label><input type="checkbox" class="os-job-step" data-id="${j.id}" data-step="${s.id}" ${s.done?'checked':''}>${esc(s.label)}</label></li>`).join('')}</ul><div class="os-actions">${j.placeId&&places.some(p=>p.id===j.placeId)?button('gotoPlace','На карте',`data-id="${j.placeId}"`,'location-dot'):''}${editableRecord(j,user)?button('job','Изменить',`data-id="${j.id}"`,'pen'):''}${button('shareJob','Отправить',`data-id="${j.id}"`,'paper-plane')}</div></div></article>`;
  const reminderList=reminders.map(r=>{
    const due=r.clock==='world'?r.due-Number(game.time.worldTime):r.due-Date.now()/1000;
    return `<label class="os-reminder ${r.done?'done':''}"><input type="checkbox" class="os-reminder-check" data-id="${r.id}" ${r.done?'checked':''}><span>${esc(r.title)}<small>${r.clock==='world'?'Игровое время':'Реальное время'} · ${r.done?'Готово':due<=0?'Срок наступил':`через ${Math.ceil(due/60)} мин.`}</small></span></label>`;
  }).join('')||'<p class="os-muted">Добавьте встречу или напоминание.</p>';
  const journalOwner=user.isGM?(device.owner||user.id):user.id;
  const journal=game.journal?.get(game.settings.get('night-city-agent','noteJournals')?.[journalOwner]);
  const notes=journal?.testUserPermission(user,'OWNER')?[...journal.pages]:[];
  const notesList=(page==='home'?notes.slice(-5):[...notes]).reverse().map(p=>button('notePage',p.name,`data-page="${esc(p.id)}" data-os-search="${searchable(p.name)}"`,'note-sticky')).join('')||'<p class="os-muted">Личные записи хранятся в вашем журнале.</p>';
  let content='';
  if(page==='home') {
    const clock=now(), active=jobs.filter(j=>!['done','archived'].includes(j.status));
    content=`<div class="os-hero"><div class="os-hero-copy"><span class="os-kicker">${esc(clock.sourceLabel)}</span><h2 class="os-clock">${esc(clock.label)}</h2><p>${esc(os.map?.weather||'НАЙТ-СИТИ · НА СВЯЗИ')}</p><span>${esc(os.map?.location||'Ваш личный терминал')}</span></div></div><div class="os-grid">`+
      section('Быстрые контакты',`<div class="os-quick-contacts">${[...contacts].sort((a,b)=>Number(!!os.contacts?.[number]?.[b.num]?.favorite)-Number(!!os.contacts?.[number]?.[a.num]?.favorite)).slice(0,4).map(c=>`<button data-action="osAction" data-os="message" data-num="${c.num}">${avatar(contactPortrait(state,number,c.num))}<strong>${esc(c.name)}</strong><small>${esc(c.num)}</small></button>`).join('')||'Контактов пока нет'}</div>`,direct('newContact','Добавить','plus'))+
      section('Последние сообщения',contacts.filter(c=>c.lastTs).slice(0,3).map(c=>`<button class="os-message-preview" data-action="osAction" data-os="message" data-num="${c.num}"><strong>${esc(c.name)} ${c.unread?badge(c.unread):''}</strong><span>${esc(c.preview)}</span></button>`).join('')||'<p class="os-muted">Сообщения появятся здесь.</p>',button('nav','Все',`data-tab="messages"`))+
      section('Кошелёк',`<div class="os-balance">${canWallet?money(actor.system.wealth.value):npcPayer?'Выплаты НПС':'Не привязан'}</div><p class="os-muted">${esc(canWallet?actor.name:npcPayer?'Перевод игрокам от имени этого контакта':'Назначьте персонажа владельцу Агента')}</p>`,button('nav','Открыть',`data-tab="wallet"`,'wallet'))+
      section('Текущая работа',active[0]?`<h3>${esc(active[0].title)}</h3><p class="os-line-clamp">${esc(active[0].body)}</p>${badge(JOB_STATES[active[0].status])}`:'<p class="os-muted">Активных заданий нет.</p>',button('nav','Задания',`data-tab="jobs"`,'list-check'))+
      section('Личные заметки',`<div class="os-note-links">${notesList}</div>`,direct('newNote','Заметка','plus'))+
      section('Ближайшие дела',reminderList,button('reminder','Напомнить','','bell'))+
      section('Городская лента',articles[0]?`<h3>${esc(articles[0].title)}</h3><p class="os-line-clamp">${esc(articles[0].body)}</p>`:'<p class="os-muted">Новости публикует мастер.</p>',button('nav','Data Pool',`data-tab="news"`,'globe'))+
      section('Места',`<p>${places.length} доступных мест · ${esc(map.title)}</p>`,button('nav','Открыть карту',`data-tab="map"`,'map'))+'</div>';
  }
  if(page==='contacts') {
    const categories=[...new Set(contacts.map(c=>os.contacts?.[number]?.[c.num]?.category).filter(Boolean))];
    content=start('Контакты','НУЖНЫЕ ЛЮДИ · В НУЖНОЕ ВРЕМЯ',direct('newContact','Добавить','plus')+direct('mailing','Рассылка','envelopes-bulk'))+search(app,'Имя, номер, категория или заметка')+`<div class="os-filters">${button('contactFilter','Все',`data-filter="" class="${!app.osContactFilter?'on':''}"`)}${button('contactFilter','Избранные',`data-filter="favorite" class="${app.osContactFilter==='favorite'?'on':''}"`,'star')}${categories.map(c=>button('contactFilter',c,`data-filter="${esc(c)}" class="${app.osContactFilter===c?'on':''}"`)).join('')}</div><div class="os-contact-list">${contacts.filter(c=>!app.osContactFilter||(app.osContactFilter==='favorite'?os.contacts?.[number]?.[c.num]?.favorite:os.contacts?.[number]?.[c.num]?.category===app.osContactFilter)).map(contactCard).join('')||empty('Здесь пока нет контактов','Добавьте номер или измените фильтр.')}</div>`;
  }
  if(page==='wallet') {
    const transactions=npcPayer?[...game.actors].flatMap(a=>Object.values(a.flags?.['night-city-agent']?.npcPayments??{}).filter(p=>p.from===number).map(p=>({...p,recipient:a.name}))).sort((a,b)=>b.createdAt-a.createdAt).map(p=>[new Date(p.createdAt).toLocaleString('ru-RU'),`${p.amount} эдди → ${p.recipient} · ${p.to}`,p.note||'Выплата от НПС']):canWallet?[...(actor.system.wealth.transactions??[])].reverse():[];
    content=start('Кошелёк','ЛИЧНЫЙ СЧЁТ · ИСТОРИЯ ПЕРЕВОДОВ',button('pay','Перевести','','money-bill-transfer')+button('split','Разделить оплату','','users'))+`<div class="os-grid">`+section(npcPayer?'Выплаты от имени НПС':'Доступные средства',`<div class="os-balance">${canWallet?money(actor.system.wealth.value):npcPayer?esc(profile.name||device.label||number):'—'}</div><p>${esc(canWallet?actor.name:npcPayer?'Мастер может начислить выплату или списать средства с выбранного листа.':'Назначьте персонажа в настройках пользователя Foundry.')}</p><p class="os-muted">${npcPayer?'Имя и номер НПС сохраняются в истории получателя.':'Баланс связан с листом персонажа.'}</p>`)+section('Регулярные расходы',`<p class="os-muted">Поставьте напоминание об аренде, питании или подписке. Списание выполняется по решению игрока и мастера.</p>${reminderList}`,button('reminder','Напоминание','','bell'))+`</div>`+section('История операций',transactions.length?`<div class="os-transactions">${transactions.map(t=>`<div>${Array.isArray(t)?t.map(v=>`<span>${esc(v)}</span>`).join(''):`<span>${esc(typeof t==='string'?t:JSON.stringify(t))}</span>`}</div>`).join('')}</div>`:empty('Операций пока нет','Переводы появятся в журнале листа персонажа.'));
  }
  if(page==='jobs') content=start('Задания','РАБОТА · ВСТРЕЧИ · НАПОМИНАНИЯ',button('job','Новое задание','','plus')+button('reminder','Напоминание','','bell'))+search(app,'Поиск заданий')+`<div class="os-filters">${button('jobFilter','Активные',`data-filter="active" class="${!app.osJobArchive?'on':''}"`)}${button('jobFilter','Завершённые и архив',`data-filter="archive" class="${app.osJobArchive?'on':''}"`)}</div><div class="os-grid os-wide-left"><div>${jobs.filter(j=>app.osJobArchive?['done','archived'].includes(j.status):!['done','archived'].includes(j.status)).map(jobCard).join('')||empty('Заданий пока нет','Создайте личное дело или дождитесь задания от мастера.')}</div>${section('Напоминания',reminderList)}</div>`;
  if(page==='map') {
    const list=places.filter(p=>!app.osMapCategory||p.category===app.osMapCategory), selected=list.find(p=>p.id===app.osPlaceId), zoom=app.osZoom||1;
    const mapMarkup=map.image?`<div class="os-map-viewport"><div class="os-map-stage" style="width:${zoom*100}%"><img class="os-map-image" src="${esc(map.image)}" alt="${esc(map.title)}">${list.map(p=>`<button type="button" class="os-map-pin ${p.id===app.osPlaceId?'on':''}" style="left:${p.x}%;top:${p.y}%" data-action="osAction" data-os="placeSelect" data-id="${p.id}" title="${esc(p.title)}" aria-label="Место: ${esc(p.title)}">${icon('location-dot')}</button>`).join('')}</div></div>`:empty('Добавьте карту вашей кампании','Мастер может загрузить изображение и расставить места по координатам в процентах.');
    content=start(map.title,'РАЙОНЫ · МЕСТА · КОНТАКТЫ',user.isGM?button('mapEdit','Карта и погода','','image')+button('defaultMap','Карта 2045','','map')+button('place','Добавить место','','location-dot'):'')+`<div class="os-map-tools"><select class="os-map-category" aria-label="Категория мест"><option value="">Все места</option>${Object.entries(PLACE_TYPES).map(([k,v])=>`<option value="${k}" ${app.osMapCategory===k?'selected':''}>${v}</option>`).join('')}</select>${button('zoomOut','Меньше','','minus')}${button('zoomReset',`Масштаб ${Math.round(zoom*100)}%`,'title="Сбросить масштаб до 100%"')}${button('zoomIn','Больше','','plus')}</div><div class="os-grid os-map-layout"><div>${mapMarkup}</div><div>${section('Места',`<div class="os-place-list">${list.map(p=>button('placeSelect',p.title,`data-id="${p.id}" class="${selected?.id===p.id?'on':''}"`,'location-dot')).join('')||'<p class="os-muted">Нет доступных меток.</p>'}</div>`)}${selected?section(selected.title,`${img(selected.image,'os-cover')}<p>${esc(selected.body)}</p>${meta('Район',selected.district)}${meta('Категория',PLACE_TYPES[selected.category])}${meta('Контакт',selected.contact)}<div class="os-actions">${button('sharePlace','Отправить место',`data-id="${selected.id}"`,'paper-plane')}${user.isGM?button('place','Изменить',`data-id="${selected.id}"`,'pen'):''}</div>`):''}</div></div>`;
  }
  if(page==='news') {
    const selected=articles.filter(a=>!app.osSavedOnly||(os.saved?.[number]??[]).includes(a.id));
    content=start('Data Pool','НОВОСТИ ГОРОДА · ОТКРЫТЫЕ ДАННЫЕ',button('newsFilter',app.osSavedOnly?'Вся лента':'Закладки','','bookmark')+(user.isGM?button('article','Публикация','','plus'):''))+search(app,'Поиск по заголовкам, тексту и источникам')+`<div class="os-news-grid">${selected.map(a=>section(a.title,`${img(a.image,'os-cover')}<div class="os-actions">${badge(a.source||'Городская лента')}${badge(a.category)}${badge(date(a.createdAt))}${!a.published?badge('Черновик мастера'):''}</div><p class="os-pre">${esc(a.body)}</p><div class="os-actions">${button('bookmark',(os.saved?.[number]??[]).includes(a.id)?'В закладках':'Сохранить',`data-id="${a.id}"`,'bookmark')}${button('articleFile','В файл',`data-id="${a.id}"`,'file-lines')}${button('shareArticle','Отправить',`data-id="${a.id}"`,'paper-plane')}${user.isGM?button('article','Изменить',`data-id="${a.id}"`,'pen'):''}</div>`).replace('<section class="os-card">',`<section class="os-card" data-os-search="${searchable(a.title+' '+a.body+' '+a.source+' '+a.category)}">`)).join('')||empty('Лента пока пуста','Мастер может публиковать новости, слухи и объявления для всей группы или выбранных получателей.')}</div>`;
  }
  if(page==='files') {
    let docs=Object.values(state.documents??{}).filter(d=>user.isGM||d.canEdit||canReadDocument(state,d,user,user.viewedScene)||!d.holders);
    const folders=[...new Set(docs.map(d=>os.fileMeta?.[number]?.[d.id]?.folder).filter(Boolean))];
    docs=docs.filter(d=>!app.osFileType||(app.osFileType==='images'?d.images?.length:app.osFileType==='favorite'?os.fileMeta?.[number]?.[d.id]?.favorite:app.osFileType==='notes'?false:true)).filter(d=>!app.osFolder||os.fileMeta?.[number]?.[d.id]?.folder===app.osFolder);
    const selected=docs.find(d=>d.id===app.osDocId),fm=os.fileMeta?.[number]?.[selected?.id]??{};
    content=start('Файлы','ЗАМЕТКИ · ЧИПЫ · УЛИКИ',button('documentNew','Новый файл','','plus')+direct('newNote','Заметка','note-sticky')+button('workspace','Терминалы',`data-tab="terminals"`,'desktop'))+search(app,'Название, текст, папка или метка')+`<div class="os-filters">${[['','Все'],['images','Изображения'],['favorite','Избранное'],['notes','Заметки']].map(([key,title])=>button('fileFilter',title,`data-filter="${key}" class="${(app.osFileType||'')===key?'on':''}"`)).join('')}<select class="os-folder-filter" aria-label="Папка"><option value="">Все папки</option>${folders.map(f=>`<option value="${esc(f)}" ${app.osFolder===f?'selected':''}>${esc(f)}</option>`).join('')}</select></div>`;
    if(app.osFileType==='notes') content+=section('Личный журнал',`<div class="os-note-links">${notesList}</div>`,direct('notes','Открыть журнал','book'));
    else content+=`<div class="os-grid os-files-layout"><div class="os-file-list">${docs.map(d=>{const m=os.fileMeta?.[number]?.[d.id]??{};return `<button class="os-file-row ${d.id===selected?.id?'on':''}" data-action="osAction" data-os="documentSelect" data-id="${d.id}" data-os-search="${searchable(d.title+' '+d.body+' '+m.folder+' '+m.tags?.join(' '))}">${icon(d.images?.length?'image':'file-lines')}<span><strong>${esc(d.title)}</strong><small>${esc(m.folder||d.source||'Файл Агента')}</small><span>${(m.tags??[]).map(badge).join('')}</span></span>${m.favorite?icon('star'):''}</button>`;}).join('')||empty('Файлов пока нет','Создайте файл или получите его от контакта.')}</div><div>${selected?section(selected.title,`${(selected.images??[]).map((im,index)=>`<button class="os-image-open" aria-label="Открыть изображение ${index+1}: ${esc(selected.title)}" data-action="osAction" data-os="documentImage" data-id="${selected.id}" data-index="${index}">${img(im.src,'os-cover')}</button>`).join('')}<p class="os-pre">${esc(selected.body)}</p>${meta('Источник',selected.source)}${meta('Папка',fm.folder)}<div class="os-actions">${(fm.tags??[]).map(badge).join('')}</div><div class="os-actions">${(user.isGM||selected.canEdit||canEditDocument(selected,user))?button('documentEdit','Редактировать',`data-id="${selected.id}"`,'pen'):''}${button('documentSend','Передать',`data-id="${selected.id}"`,'paper-plane')}${button('fileMeta','Метки и папка',`data-id="${selected.id}"`,'tags')}${button('documentExport','Экспорт',`data-id="${selected.id}"`,'download')}${button('documentWorkspace','На носитель',`data-id="${selected.id}"`,'microchip')}</div>`):empty('Выберите файл','Текст и изображения откроются здесь.')}</div></div>`;
  }
  if(page==='calls') {
    const statuses={ringing:'Ожидание ответа',active:'На связи',ended:'Завершён'};
    const replies={invited:'Приглашён',accepted:'На связи',declined:'Отклонён',left:'Вышел'};
    const name=n=>monitoring?(os.profiles?.[n]?.name||state.devices[n]?.label||n):contactName(n);
    const stamp=ts=>new Date(ts).toLocaleString('ru-RU',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'});
    const filtered=calls.filter(c=>!app.osCallFilter||(app.osCallFilter==='active'?c.status!=='ended':c.status==='ended'));
    const call=filtered.find(c=>c.id===app.osCallId)||filtered.find(c=>c.status!=='ended');
    content=start(monitoring?'Звонки · пульт мастера':'Вызовы',monitoring?'ВСЕ АГЕНТЫ · УЧАСТНИКИ · СОСТОЯНИЕ':'ЛИЧНАЯ СВЯЗЬ · СЦЕНИЧЕСКИЙ РЕЖИМ',button('call','Новый вызов','','phone'))+
      `<p class="os-call-notice">Игровой вызов с приглашением и портретами. Голос — в вашем обычном голосовом чате; микрофон и камера здесь не передаются.</p>`+
      (user.isGM?`<div class="os-filters">${button('callScope','Все Агенты',`data-scope="all" class="${monitoring?'on':''}"`,'tower-broadcast')}${button('callScope','Текущий Агент',`data-scope="mine" class="${!monitoring?'on':''}"`)}</div>`:'')+
      `<div class="os-filters">${button('callFilter','Все',`data-filter="" class="${!app.osCallFilter?'on':''}"`)}${button('callFilter',`Активные · ${activeCallCount}`,`data-filter="active" class="${app.osCallFilter==='active'?'on':''}"`)}${button('callFilter','Завершённые',`data-filter="ended" class="${app.osCallFilter==='ended'?'on':''}"`)}</div>`;
    if(call) {
      const member=call.members.includes(number);
      content+=`<div class="os-call-stage"><div class="os-card-head"><h3>${call.status==='ended'?'Разговор завершён':statuses[call.status]}</h3><span class="os-call-timer" data-start="${call.startedAt||call.createdAt}" data-end="${call.endedAt||''}"></span></div><p class="os-muted">Инициатор: ${esc(name(call.from))} · ${esc(call.from)} · ${esc(stamp(call.createdAt))}</p><div class="os-call-members">${call.members.map(n=>`<article>${avatar(contactPortrait(state,number,n)||os.profiles?.[n]?.avatar)}<h3>${esc(!monitoring&&n===number?'Вы':name(n))}</h3><small>${esc(n)} · ${replies[call.replies[n]]||''}</small></article>`).join('')}</div><div class="os-actions">${member&&call.status!=='ended'&&call.from!==number&&call.replies[number]==='invited'?button('callReply','Принять',`data-id="${call.id}" data-reply="accepted"`,'phone')+button('callReply','Отклонить',`data-id="${call.id}" data-reply="declined"`,'phone-slash'):''}${member&&call.status!=='ended'&&call.replies[number]==='accepted'?button('callInvite','Пригласить',`data-id="${call.id}"`,'user-plus')+direct('newNote','Заметка','note-sticky')+button('nav','Файлы',`data-tab="files"`,'folder-open'):''}${call.status!=='ended'?(call.from===number||user.isGM?button('callEnd',monitoring?'Завершить вызов':'Завершить',`data-id="${call.id}" class="os-danger"`,'phone-slash'):member&&call.replies[number]==='accepted'?button('callReply','Выйти',`data-id="${call.id}" data-reply="left"`,'phone-slash'):''):''}</div></div>`;
    } else content+=empty(monitoring?'Нет выбранного звонка':'Вы на связи','Выберите разговор из списка или начните новый.');
    content+=search(app,'Поиск звонка по имени или номеру')+section(monitoring?'Все звонки игроков и НПС':'История вызовов',`<div class="os-call-list">${filtered.map(c=>`<div data-os-search="${searchable(c.members.map(n=>name(n)+' '+n).join(' '))}">${button('callSelect',`${stamp(c.createdAt)} · ${c.members.map(name).join(', ')} · ${statuses[c.status]}`,`data-id="${c.id}" aria-pressed="${call?.id===c.id}" class="${call?.id===c.id?'on':''}"`,'phone')}</div>`).join('')||'<p class="os-muted">Вызовов пока нет.</p>'}</div>`);
  }
  if(page==='settings') {
    const items=actor&&(user.isGM||actor.isOwner)?[...actor.items].filter(i=>['cyberware','weapon','gear'].includes(i.type)):[];
    content=start('Профиль и устройства','НАСТРОЙТЕ СВОЙ АГЕНТ',direct('help','Руководство','circle-question'))+`<div class="os-grid">`+section('Профиль',`<div class="os-profile">${avatar(profile.avatar)}<div><h3>${esc(profile.name||device.label||number)}</h3><p>${esc(profile.role)}</p><span>${esc(number)}</span></div></div><p>${esc(profile.bio)}</p><small class="os-muted">Портрет и описание видны знакомым контактам.</small>`,button('profile','Изменить','','pen'))+
      section('Оформление',`<label class="os-switch"><input type="checkbox" class="os-compact-toggle" ${app.osCompact?'checked':''}> Компактный корпус</label><label class="os-switch"><input type="checkbox" class="os-motion-toggle" ${app.osReducedMotion?'checked':''}> Уменьшить эффекты</label><p class="os-muted">Настройки сохраняются на этом устройстве.</p><div class="os-actions">${direct('pickRingtone','Рингтон','music')}${device.ringtone?direct('resetRingtone','Общий звук','volume-high'):''}</div>`)+
      section('Данные и доступ',`${meta('Хранилище',protectedStorage()?'Защита хранения включена':'Совместимый режим')}${meta('Тип устройства',device.kind==='internal'?'Внутренний Агент':'Карманный Агент')}${meta('Связь с мастером',game.users.activeGM?'Установлена':'Мастер не в игре')}<div class="os-actions">${user.isGM?direct('data','Копии и восстановление','shield-halved'):''}${direct('emergency','Экстренные службы','truck-medical')}</div>`)+
      section('Связанный персонаж',actor?`${meta('Персонаж',actor.name)}${meta('Предметов в обзоре',items.length)}<div class="os-actions">${button('actor','Открыть лист','','id-card')}</div>`:'<p>Назначьте персонажа пользователю Foundry. Если листов несколько, выберите нужный токен.</p>')+`</div>`+section('Импланты и снаряжение',`<p class="os-muted">Обзор доступных предметов листа. Открывайте предмет для управления его функциями.</p><div class="os-equipment">${items.slice(0,100).map(i=>`<button data-action="osAction" data-os="item" data-id="${esc(i.id)}">${img(i.img)}<span>${esc(i.name)}<small>${({cyberware:'Киберимплант',weapon:'Оружие',gear:'Снаряжение'})[i.type]}</small></span></button>`).join('')||'Нет связанного снаряжения.'}</div>`);
  }
  return {osContent:content,osNav:nav,osMessages:page==='messages',osCompact:app.osCompact,osReducedMotion:app.osReducedMotion,osStatus:`${game.users.activeGM?'CitiNET · связь установлена':'CitiNET · мастер не в игре'}`,osName:profile.name||device.label||'АГЕНТ',osActiveAvatar:contactPortrait(state,number,app.other)};
}
